version: 0.2

env:
  variables:
    SERVERLESS_ACCESS_KEY: AKNL0W6THJJoFgej8XmjSDJsw7rI3ycbFPVfQMv53XMqt

phases:
  install:
    commands:
      - echo Installing Serverless
      - npm install -g serverless

  pre_build:
    commands:
      - echo Install source NPM dependencies
      - npm install

  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying the Serverless Framework
      - sls deploy  -s $ENV_NAME

  post_build:
    commands:
      - echo Deployment completed on `date`
